language: node_js
node_js:
    - 7
    - node
cache:
    directories:
        - node_modules
        - frontend/node_modules
install:
    - npm install
    - cd frontend/ && npm install && cd ../
script:
    - cd frontend/
    - npm test
    - npm run build
